server:
  port: 9090

spring:
  application:
    name: gestion-eventos
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
glpi:
  base-url: ${BASE_URL}
  app-token: ${APP_TOKEN}
  user-token: ${USER_TOKEN}

