server:
  port: 9090

spring:
  application:
    name: gestion-eventos
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
glpi:
  base-url: http://glpi.local/apirest.php
  app-token: fNhHOxchUasACOurhOzfWjEzCk0rnDKmjqNqxccr
  user-token: NvrL7CikJE3KyL6WW7UfOPoZpczj40FoNLS6YVn7

